# Generated by Django 2.2.3 on 2019-09-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
